apiVersion: apps/v1
kind: Deployment
metadata:
 name: cpp-deployment
spec:
 replicas: 3
 selector:
   matchLabels:
     app: cpp
 template:
   metadata:
     labels:
       app: cpp
   spec:
     containers:
     - name: dispatcher
       image: antonpet/crawlers
       ports:
       - name: grpc
         containerPort: 9090
