// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: info.proto

#include "info.pb.h"
#include "info.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace cloudcrawler {

static const char* Dispatcher_method_names[] = {
  "/cloudcrawler.Dispatcher/GetUrl",
  "/cloudcrawler.Dispatcher/AddUrl",
  "/cloudcrawler.Dispatcher/SaveService",
};

std::unique_ptr< Dispatcher::Stub> Dispatcher::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Dispatcher::Stub> stub(new Dispatcher::Stub(channel, options));
  return stub;
}

Dispatcher::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetUrl_(Dispatcher_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AddUrl_(Dispatcher_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SaveService_(Dispatcher_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Dispatcher::Stub::GetUrl(::grpc::ClientContext* context, const ::cloudcrawler::Empty& request, ::cloudcrawler::GetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::cloudcrawler::Empty, ::cloudcrawler::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetUrl_, context, request, response);
}

void Dispatcher::Stub::async::GetUrl(::grpc::ClientContext* context, const ::cloudcrawler::Empty* request, ::cloudcrawler::GetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::cloudcrawler::Empty, ::cloudcrawler::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetUrl_, context, request, response, std::move(f));
}

void Dispatcher::Stub::async::GetUrl(::grpc::ClientContext* context, const ::cloudcrawler::Empty* request, ::cloudcrawler::GetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetUrl_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::cloudcrawler::GetResponse>* Dispatcher::Stub::PrepareAsyncGetUrlRaw(::grpc::ClientContext* context, const ::cloudcrawler::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::cloudcrawler::GetResponse, ::cloudcrawler::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetUrl_, context, request);
}

::grpc::ClientAsyncResponseReader< ::cloudcrawler::GetResponse>* Dispatcher::Stub::AsyncGetUrlRaw(::grpc::ClientContext* context, const ::cloudcrawler::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetUrlRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Dispatcher::Stub::AddUrl(::grpc::ClientContext* context, const ::cloudcrawler::AddRequest& request, ::cloudcrawler::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::cloudcrawler::AddRequest, ::cloudcrawler::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AddUrl_, context, request, response);
}

void Dispatcher::Stub::async::AddUrl(::grpc::ClientContext* context, const ::cloudcrawler::AddRequest* request, ::cloudcrawler::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::cloudcrawler::AddRequest, ::cloudcrawler::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddUrl_, context, request, response, std::move(f));
}

void Dispatcher::Stub::async::AddUrl(::grpc::ClientContext* context, const ::cloudcrawler::AddRequest* request, ::cloudcrawler::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddUrl_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::cloudcrawler::Empty>* Dispatcher::Stub::PrepareAsyncAddUrlRaw(::grpc::ClientContext* context, const ::cloudcrawler::AddRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::cloudcrawler::Empty, ::cloudcrawler::AddRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AddUrl_, context, request);
}

::grpc::ClientAsyncResponseReader< ::cloudcrawler::Empty>* Dispatcher::Stub::AsyncAddUrlRaw(::grpc::ClientContext* context, const ::cloudcrawler::AddRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddUrlRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Dispatcher::Stub::SaveService(::grpc::ClientContext* context, const ::cloudcrawler::Empty& request, ::cloudcrawler::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::cloudcrawler::Empty, ::cloudcrawler::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SaveService_, context, request, response);
}

void Dispatcher::Stub::async::SaveService(::grpc::ClientContext* context, const ::cloudcrawler::Empty* request, ::cloudcrawler::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::cloudcrawler::Empty, ::cloudcrawler::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SaveService_, context, request, response, std::move(f));
}

void Dispatcher::Stub::async::SaveService(::grpc::ClientContext* context, const ::cloudcrawler::Empty* request, ::cloudcrawler::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SaveService_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::cloudcrawler::Empty>* Dispatcher::Stub::PrepareAsyncSaveServiceRaw(::grpc::ClientContext* context, const ::cloudcrawler::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::cloudcrawler::Empty, ::cloudcrawler::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SaveService_, context, request);
}

::grpc::ClientAsyncResponseReader< ::cloudcrawler::Empty>* Dispatcher::Stub::AsyncSaveServiceRaw(::grpc::ClientContext* context, const ::cloudcrawler::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSaveServiceRaw(context, request, cq);
  result->StartCall();
  return result;
}

Dispatcher::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Dispatcher_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Dispatcher::Service, ::cloudcrawler::Empty, ::cloudcrawler::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Dispatcher::Service* service,
             ::grpc::ServerContext* ctx,
             const ::cloudcrawler::Empty* req,
             ::cloudcrawler::GetResponse* resp) {
               return service->GetUrl(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Dispatcher_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Dispatcher::Service, ::cloudcrawler::AddRequest, ::cloudcrawler::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Dispatcher::Service* service,
             ::grpc::ServerContext* ctx,
             const ::cloudcrawler::AddRequest* req,
             ::cloudcrawler::Empty* resp) {
               return service->AddUrl(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Dispatcher_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Dispatcher::Service, ::cloudcrawler::Empty, ::cloudcrawler::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Dispatcher::Service* service,
             ::grpc::ServerContext* ctx,
             const ::cloudcrawler::Empty* req,
             ::cloudcrawler::Empty* resp) {
               return service->SaveService(ctx, req, resp);
             }, this)));
}

Dispatcher::Service::~Service() {
}

::grpc::Status Dispatcher::Service::GetUrl(::grpc::ServerContext* context, const ::cloudcrawler::Empty* request, ::cloudcrawler::GetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Dispatcher::Service::AddUrl(::grpc::ServerContext* context, const ::cloudcrawler::AddRequest* request, ::cloudcrawler::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Dispatcher::Service::SaveService(::grpc::ServerContext* context, const ::cloudcrawler::Empty* request, ::cloudcrawler::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace cloudcrawler

